### PR TITLE
Fixed a typo in the property name.

### PR DESCRIPTION
**Pull request by tastle**
This appears to be a typo in the test.

### CODE REVIEW

**Comment by lorebiga** [comment]
I've seen there's other cases like this ('/' at the beginning of a property name). No misfunctioning has been reported though, what are you experiencing? Thanks for your feedback.

**Comment by tastle** [comment]
Hi @lorebiga ,

I'm experiencing a test failure on that property.  In the CSW, I have an ows:Boundingbox, but I don't have an "/ows:BoundingBox".

I'm trying to understand why the test would have a forward slash prefix as part of the PropertyName.  Either the CSW that the test ran again actually had a property "/ows:BoundingBox" or, more likely it assumes a property is passed into an XPath engine.  That seems to correlate to the CSW 2.0.2, Corrigendum 2 Release of the specification:

> 10.8.4.11.5 Property references 
> The <ogc:PropertyName>element is used in Filter expressions to reference properties 
> from the information model of a catalogue. If the catalogue's information model is being 
> realized as an XML document with an accompanying XML Schema, then XPath 
> expressions shall be used to reference the various metadata properties.

But I'm left a bit confused.  The example in the specification is as follows:

> <ogc:PropertyName>ows:BoundingBox</ogc:PropertyName>

and in the case where they do an XPath query, it's as follows

> <ogc:PropertyName>/csw:Record/dct:modified</ogc:PropertyName>

Since you mentioned other cases of forward slashes, I ran the following in the ctl directory:
`findstr /S /c:"PropertyName" *.xml`

So I'm not even sure how either /ows:BoundingBox or /dc:title would be considered valid XPath queries?  Wouldn't the ows:BoundingBox have to be the first element from the root for it to work?
The example XPath in the specification makes sense to me, not what is in the test.

I'm thinking that the purpose of this test (and I guess the /dc:title tests too) aren't about verifying if XPath queries work, I assumed the aligning the tests to match the examples in the specification made the most sense, thus this pull request.

Of course, I might be missing obvious, so please let me know where I'm mistaken.

**Comment by lorebiga** [comment]
Hi @tastle, I've examined this and I think you are right: the XPath wouldn't be correct.
I assume that compliant instances have so far extracted the property name from the string, without applying it as an XPath expression...
Anyway, I'm also removing the '/' from the other occurrences.

**Comment by trophies** [comment]
Thanks @lorebiga, unfortunately @tastle is no longer with us.  He ascended to the [(Marketing) Cloud](http://www.salesforce.com).

**Comment by tastle** [comment]
@lorebiga , thanks!
@trophies , it's amazing up here.  Not only do you get a great view from up in the cloud, but you can also throw lightning bolts at people.  Ker-smash!  ;-)

**Pull request merged**
